language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install -g bower polymer-cli
  - npm install
  - bower install
  - polymer install
before_script:
  - npm run lint
script:
  - npm run start
