language: node_js
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
node_js:
- node
- '6'
cache:
  directories:
  - node_modules
install:
- npm install -g bower polymer-cli
- npm install
- bower install
- polymer install
script:
- npm run lint
before_deploy:
- polymer build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: qmdddC4998RlD2clUH7FDT8NyD0oR1m+r977BiPKt7Zby9JSSWkGDocNx3dv6MuKjmB3RR64hcG4gszbopLnAG3GhO//NRlkyLfWPhtuDkKqrpcF9/2awNJ1eJhUiK2mbmNCEOV4FvfRO4Bn72oJ+NHAEmPnlSoj6ocBRS2OLFvGlhNc8JDl9U8TJ0hx3J511SjycyypCEeh1jge34n20xXQt+PxG4Yiu8JAakPDgKEJpmw7hZ9DssVg4XddYkCqZI8+m9t6XngauD2LWtO1CtHvKhdIXRfbrBci7smNjym7bQftKF1Tb6AUi9UTbGVZYceSk5zVYCU4uNzVBwQI50A7Oi1iMhkqOCtQJm+6imTHOyy9a/FpXXFxtwAUz9Uoidl2vkfm5mIzx3KeSDQ9ky+0wzeV9L0rP+EiGBj4hOjaudOtAEyOvIN7ZBD4eKEv8LPdmiWrF8isx44P7sPLCRrV58OqSgdwCwtjxT7RPH+ef2JBbeZBASpXaMj8piHAWEciWw1o+FWlE+mfY5hsuQTCERUdPWbn4qEWuLxsNuW/tGyXB65d6sjLSddu4bAqCSe2oQceVnYzIWGaauqMIiFemDgJzxSRws+Y8m8MA63eoFC546BfGASSimSjRvRvn+yuyE13VtX7gI+ZoCV/1H7u0E9RikIO2CcJNb6yWN4=
  message: The Deployment is being done! I guess?!
  on:
    branch: master
env:
  global:
    secure: eGvN4Xqr8YDk4pTJQ25zeie3bw33iPxGJQFmFe4hrS6XD3efc897lPhmH5BFJ2c0GBF9nH0gG0uuvwtbWLkhqMN7ogKp9nplPOybO7+OxeRvvkMHfmyu5xGET6T/Z/2rnRBG8VSBj2kcn2QCKVC8vj4CeYGwZruiwGiSGXLskVi9NIzGDW8OqaZPl7AwQeQIW7/CoUlTmwDIvGE+CJ8ZbrikF9PcDVhq2lNVMGpQbjhHLka8Dj2I6wI3kYZsrRiPjVQw6Dn6K7auQPk9flMpxzZixOn8iFiSdKg+tRRdlMqTChwBQME3DkAvYPe0bOaJ8JxilS+tKSjyb2e2gT7xJWB3d7sq658KILATsZSoJfBLtr0AQPYcLdoCnVjfg2gn4fn53QwddYVk4lyAi8eGziSD4X0SDb/WVDo0EEhI7suQIf/RzgLJbegZKAZvUt1c8cdzgK4i3xHOMF3o8vAFZdooBAdV2ej/QOdfRx9OULcXNDFA5iwJy5Ip6IqbNm84qe/16fLxL4w5Flmy0n7SXwSwcWZvxspjvpV2rvCnr090DEXtewSShN22teaTdFIWOC5kMCqZHMDw357Lz+7P77RkGdMq6TToBl6eajDyYuXJUeEAlrxZpLqe3BKizIhEXnW4oKDUuyX+02DffRO3d4RvqeVw/l9ftcRNbcXB3Og=
